//
//  RootTableViewControllerPresenter.swift
//  TestWeather
//
//  Created Алла Даминова on 15.07.2021.
//  Copyright © 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  Template generated by Edward
//

import Foundation

// MARK: View -
protocol RootTableViewControllerViewProtocol: class {

}

// MARK: Presenter -
protocol RootTableViewControllerPresenterProtocol: class {
	var view: RootTableViewControllerViewProtocol? { get set }
    var weatherCitys: [WeatherModel]? { get set }
    init(view: RootTableViewControllerViewProtocol, networkService: NetworkServiceProtocol, router: RouterProtocol)
    func downloadCity()
    func tapOnTheCity(city: WeatherModel)
    func deleteCity(city: WeatherModel)
    func addCity(city: WeatherModel)
}

class RootTableViewControllerPresenter: RootTableViewControllerPresenterProtocol {

    
    weak var view: RootTableViewControllerViewProtocol?
    var comments: [WeatherModel]?
    var router: RouterProtocol?
    weak var networkService: NetworkServiceProtocol?
    
    required init(view: RootTableViewControllerViewProtocol, networkService: NetworkServiceProtocol, router: RouterProtocol) {
        self.view = view
        self.networkService = networkService
        self.router = router
        downloadCity()
    }
    
    var weatherCitys: [WeatherModel]?
    
    func downloadCity() {
        
    }
    
    func tapOnTheCity(city: WeatherModel) {
        
    }
    
    func deleteCity(city: WeatherModel) {
        
    }
    
    func addCity(city: WeatherModel) {
        
    }
}
